name: flow
params:
  metadata:

    - layer: projector
      inputs:
        - src
      outputs:
        - x
        - y

    - layer: encoder
      inputs:
        - src
        - x
        - y
      outputs:
        - res

  layers:

    projector:
      model: ggpd.GPProjector
      params:
        in_channels: 3
        out_channels: 
          - 3
          - 3
        alg: mix
        num_blocks:
          - 2
          - 2

    encoder:
      model: ggpd.GPEncoder
      params:
        in_channels: 3
        out_channels: 3
        alg: mix
        num_blocks:
          - 2
          - 2
