task: train
experiment: ggpd.msab.huawei
save_dir: .experiments
accelerator: gpu
devices: [0]
resume: True
epochs: 5800
save_freq: 1
visualize_freq: 1

defaults:
  - model: ggpd
  - data: huawei
  - pipeline: ggpd
  - _self_
